version: '3'

services:
  golang:
    build: ./docker
    volumes:
      - .:/go/src/github.com/api
    tty: true
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    container_name: golang-container
    environment:
      MODE: "develop"

  redis:
    image: redis
    ports:
      - 6379:6379
    command: redis-server
    container_name: redis-container

  # mysql のサービスを追加
  mysql:
    image: mysql:5.7.22
    ports:
      - '13306:3306'

    # 日本語のデータを送った時に文字化けしてしまうので必ず必要
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/data:/var/log/mysql
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    container_name: mysql-container

